[build]
  publish = "build"
  functions = "functions"

[[redirects]]
  from = "/auth/callback"
  to = "/api/shopify/callback"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
